node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.0/run312 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.0/run312/run312-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.0/run314 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.0/run314/run314-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.0/run315 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.0/run315/run315-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.0/run316 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.0/run316/run316-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.0/run317 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.0/run317/run317-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.25/run348 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.25/run348/run348-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.25/run350 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.25/run350/run350-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.25/run351 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.25/run351/run351-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.25/run352 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.25/run352/run352-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.25/run353 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.25/run353/run353-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.5/run318/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.5/run318/run318-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.5/run319/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.5/run319/run319-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.5/run320/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.5/run320/run320-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.5/run321/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.5/run321/run321-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-0.5/run322/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-0.5/run322/run322-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-1.0/run341/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-1.0/run341/run341-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-1.0/run342/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-1.0/run342/run342-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-1.0/run343/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-1.0/run343/run343-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-1.0/run345/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-1.0/run345/run345-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-1.0/run347/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-1.0/run347/run347-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-13b-instruct/template-full-0.0/run354/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-13b-instruct/template-full-0.0/run354/run354-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-13b-instruct/template-full-0.0/run355/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-13b-instruct/template-full-0.0/run355/run355-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-13b-instruct/template-full-0.0/run356/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-13b-instruct/template-full-0.0/run356/run356-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-13b-instruct/template-full-0.0/run358/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-13b-instruct/template-full-0.0/run358/run358-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-13b-instruct/template-full-0.0/run359/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-13b-instruct/template-full-0.0/run359/run359-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/mixtral-8x7b-instruct/template-full-0.0/run360/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/mixtral-8x7b-instruct/template-full-0.0/run360/run360-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/mixtral-8x7b-instruct/template-full-0.0/run361/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/mixtral-8x7b-instruct/template-full-0.0/run361/run361-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/mixtral-8x7b-instruct/template-full-0.0/run362/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/mixtral-8x7b-instruct/template-full-0.0/run362/run362-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/mixtral-8x7b-instruct/template-full-0.0/run363/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/mixtral-8x7b-instruct/template-full-0.0/run363/run363-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/mixtral-8x7b-instruct/template-full-0.0/run364/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/mixtral-8x7b-instruct/template-full-0.0/run364/run364-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/gpt-4o-mini/template-full-0.0/run58/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/gpt-4o-mini/template-full-0.0/run58/run58-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/gpt-4o-mini/template-full-0.0/run59/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/gpt-4o-mini/template-full-0.0/run59/run59-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/gpt-4o-mini/template-full-0.0/run60/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/gpt-4o-mini/template-full-0.0/run60/run60-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/gpt-4o-mini/template-full-0.0/run61/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/gpt-4o-mini/template-full-0.0/run61/run61-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/gpt-4o-mini/template-full-0.0/run63/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/gpt-4o-mini/template-full-0.0/run63/run63-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/llama-3.3-70b-instruct/template-full-0.0/run23/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/llama-3.3-70b-instruct/template-full-0.0/run23/run23-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/llama-3.3-70b-instruct/template-full-0.0/run24/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/llama-3.3-70b-instruct/template-full-0.0/run24/run24-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/llama-3.3-70b-instruct/template-full-0.0/run25/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/llama-3.3-70b-instruct/template-full-0.0/run25/run25-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/llama-3.3-70b-instruct/template-full-0.0/run26/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/llama-3.3-70b-instruct/template-full-0.0/run26/run26-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/llama-3.3-70b-instruct/template-full-0.0/run27/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/llama-3.3-70b-instruct/template-full-0.0/run27/run27-costs-table.tex


node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noexplanation-0.0/run372 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noexplanation-0.0/run372/run372-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noexplanation-0.0/run374 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noexplanation-0.0/run374/run374-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noexplanation-0.0/run375 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noexplanation-0.0/run375/run375-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noexplanation-0.0/run376 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noexplanation-0.0/run376/run376-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noexplanation-0.0/run377 > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noexplanation-0.0/run377/run377-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noinstructions-0.0/run378/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noinstructions-0.0/run378/run378-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noinstructions-0.0/run379/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noinstructions-0.0/run379/run379-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noinstructions-0.0/run380/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noinstructions-0.0/run380/run380-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noinstructions-0.0/run381/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noinstructions-0.0/run381/run381-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-noinstructions-0.0/run382/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-noinstructions-0.0/run382/run382-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-onemutation-0.0/run365/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-onemutation-0.0/run365/run365-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-onemutation-0.0/run366/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-onemutation-0.0/run366/run366-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-onemutation-0.0/run369/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-onemutation-0.0/run369/run369-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-onemutation-0.0/run370/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-onemutation-0.0/run370/run370-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-basic-0.0/run390/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-basic-0.0/run390/run390-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-basic-0.0/run391/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-basic-0.0/run391/run391-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-basic-0.0/run392/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-basic-0.0/run392/run392-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-basic-0.0/run393/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-basic-0.0/run393/run393-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-basic-0.0/run394/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-basic-0.0/run394/run394-costs-table.tex

node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run384/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run384/run384-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run385/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run385/run385-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run386/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run386/run386-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run387/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run387/run387-costs-table.tex
node benchmark/generateCostsTable.js /Users/franktip/git/mutation-testing-data/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run388/ > ~/git/mutation-testing-paper/tse2024-MajorRevision/supplemental/codellama-34b-instruct/template-full-genericsystemprompt-0.0/run388/run388-costs-table.tex






